class LocalizationService {
  static const Map<String, Map<String, String>> _localizedStrings = {
    'en': {
      'register': 'Register',
      'english': 'English',
      'greek': 'Greek',
      'student_registration': 'Student Registration',
      'details': 'Details',
      'education': 'Education',
      'parents_info': 'Parents Info',
      'parents_address': "Parents' Address",
      'name': 'Name',
      'family_name': 'Family Name',
      'father_name': "Father's Name",
      'mother_name': "Mother's Name",
      'birth_date': 'Birth Date (dd/mm/yyyy)',
      'birth_place': 'Place of Birth',
      'id_card_number': 'ID Card Number',
      'issuing_authority': 'Issuing Authority',
      'university': 'University',
      'department': 'Department of Study',
      'year_of_study': 'Year of Study',
      'has_other_degree': 'Having any other degree?',
      'yes': 'Yes',
      'no': 'No',
      'email': 'Email',
      'phone': 'Phone Number',
      'tax_number': 'Tax Number (AFM)',
      'father_job': "Father's Job",
      'mother_job': "Mother's Job",
      'address': 'Address',
      'city': 'City',
      'region': 'Region',
      'postal_code': 'Postal Code',
      'country': 'Country',
      'number': 'Number',
      'required': 'Required',
      'select_birth_date': 'Select your birth date',
      'registration_complete': 'Registration Complete',
      'registration_submitted': 'Your registration has been submitted.',
      'ok': 'OK',
      'back': 'Back',
      'dark': 'Dark',
      'light': 'Light',
      'dismiss': 'Dismiss',
    },
    'el': {
      'register': 'Εγγραφή',
      'english': 'Αγγλικά',
      'greek': 'Ελληνικά',
      'student_registration': 'Εγγραφή Φοιτητή',
      'details': 'Στοιχεία',
      'education': 'Εκπαίδευση',
      'parents_info': 'Στοιχεία Γονέων',
      'parents_address': 'Διεύθυνση Γονέων',
      'name': 'Όνομα',
      'family_name': 'Επώνυμο',
      'father_name': 'Όνομα Πατέρα',
      'mother_name': 'Όνομα Μητέρας',
      'birth_date': 'Ημερομηνία Γέννησης (ηη/μμ/εεεε)',
      'birth_place': 'Τόπος Γέννησης',
      'id_card_number': 'Αριθμός Ταυτότητας',
      'issuing_authority': 'Αρχή Έκδοσης',
      'university': 'Πανεπιστήμιο',
      'department': 'Τμήμα Σπουδών',
      'year_of_study': 'Έτος Σπουδών',
      'has_other_degree': 'Διαθέτετε άλλο πτυχίο;',
      'yes': 'Ναι',
      'no': 'Όχι',
      'email': 'Email',
      'phone': 'Τηλέφωνο',
      'tax_number': 'ΑΦΜ',
      'father_job': 'Επάγγελμα Πατέρα',
      'mother_job': 'Επάγγελμα Μητέρας',
      'address': 'Διεύθυνση',
      'city': 'Πόλη',
      'region': 'Περιοχή',
      'postal_code': 'Τ.Κ.',
      'country': 'Χώρα',
      'number': 'Αριθμός',
      'required': 'Υποχρεωτικό',
      'select_birth_date': 'Επιλέξτε ημερομηνία γέννησης',
      'registration_complete': 'Η εγγραφή ολοκληρώθηκε',
      'registration_submitted': 'Η εγγραφή σας υποβλήθηκε.',
      'ok': 'OK',
      'back': 'Πίσω',
      'dark': 'Σκοτεινό',
      'light': 'Φωτεινό',
      'dismiss': 'Απόρριψη',
    },
  };

  static String t(String lang, String key) =>
      _localizedStrings[lang]?[key] ?? key;

  static Map<String, String> getTranslations(String lang) =>
      _localizedStrings[lang] ?? _localizedStrings['en']!;

  static List<String> get supportedLocales => _localizedStrings.keys.toList();
}
