name: Bug Report
description: Report a bug or issue with OIKAD
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below to help us understand and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the issue you're experiencing...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Drag and drop images here or click to upload

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform are you using?
      options:
        - Android
        - iOS
        - Web
        - Windows
        - macOS
        - Linux
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device/Browser
      description: Device model or browser name
      placeholder: e.g., Samsung Galaxy S21, iPhone 13, Chrome 120
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: Operating system version
      placeholder: e.g., Android 12, iOS 16.1, Windows 11
    validations:
      required: true

  - type: input
    id: app-version
    attributes:
      label: App Version
      description: Version of OIKAD you're using
      placeholder: e.g., v1.1.1
    validations:
      required: true

  - type: dropdown
    id: frequency
    attributes:
      label: Frequency
      description: How often does this bug occur?
      options:
        - Always
        - Often (more than 50% of the time)
        - Sometimes (less than 50% of the time)
        - Rarely
        - Once
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (app crashes, data loss)
        - High (major feature broken)
        - Medium (feature partially broken)
        - Low (minor issue, workaround available)
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: If applicable, paste any error messages or logs
      placeholder: Paste error logs here...
      render: text

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported before
          required: true
        - label: I have provided all the required information above
          required: true
        - label: I understand that incomplete bug reports may be closed without investigation
          required: true
